language: node_js

sudo: required

matrix:
  include:
    - os: osx
      node_js: 10
      env:
        - OPENCV4NODEJS_AUTOBUILD_OPENCV_VERSION=4.4.0
    - os: linux
      node_js: 10
      env:
        - OPENCV4NODEJS_AUTOBUILD_OPENCV_VERSION=4.4.0

before_install:
  - "./setup_${TRAVIS_OS_NAME}.sh"
install:
  - npm install

script:
  - npm test
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/nut-tree/opencv4nodejs
  - cd opencv4nodejs
  - export OPENCV4NODEJS_PREBUILT_SKIP_DEPENDENCIES=1
  # install new opencv-build version
  - npm install $TRAVIS_BUILD_DIR
  - npm install
  - cd test
  - npm install
  - npm run test
  - unset OPENCV4NODEJS_PREBUILT_SKIP_DEPENDENCIES

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - npm whoami
  - cd $TRAVIS_BUILD_DIR
  - bsdtar -czf opencv-build.tar -h -C .. -T "package_${TRAVIS_OS_NAME}.txt"

deploy:
  provider: script
  skip_cleanup: true
  script: npm publish opencv-build.tar
  on:
    tags: true
