language: node_js
node_js:
  - 10
sudo: required
matrix:
  include:
    - os: linux
    - os: osx
before_install:
  - "./setup_${TRAVIS_OS_NAME}.sh"
install:
  - OPENCV_ENABLE_AUTOBUILD=1 npm install
  - npm test

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - npm whoami
  - bsdtar -czf opencv-build.tar -h -C .. -T package.txt

deploy:
  provider: script
  skip_cleanup: true
  script: npm publish opencv-build.tar
  on:
    tags: true
    branch: master
