language: node_js

node_js:
  - 10

sudo: required

matrix:
  include:
    - os: linux
    - os: osx

before_install:
  - ./setup_${TRAVIS_OS_NAME}.sh

install:
  # install and run tests of opencv-build
  - OPENCV_ENABLE_AUTOBUILD=1 npm install
  - npm test

  # install opencv4nodejs and run tests
  - git clone https://github.com/nut-tree/opencv4nodejs
  - cd opencv4nodejs
  - git checkout opencv-prebuilt
  # uninstall npm version of opencv-build
  - npm uninstall opencv-build
  # install new opencv-build version
  - npm install ../
  - npm install
  - cd test
  - npm install
