platform:
  - x64

image:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: 10

clone_folder: c:\projects\opencv-build

install:
  - cmd: choco install cmake -y
  - cmd: choco upgrade cmake
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
  - SET PATH=%PATH%;C:\Program Files\CMake\bin;

build: off

test_script:
  # install and run tests of opencv-build
  - cd c:\projects\opencv-build
  - SET OPENCV_ENABLE_AUTOBUILD=1
  - npm install
  - npm test

on_success:
  - cmd: cd c:\projects\opencv-build
  - IF defined APPVEYOR_REPO_TAG_NAME npm publish

  # install opencv4nodejs and run tests
  # - cd c:\projects
  # - git clone https://github.com/nut-tree/opencv4nodejs
  # - cd opencv4nodejs
  # - git checkout opencv-prebuilt
  # uninstall npm version of opencv-build
  # - npm uninstall opencv-build
  # install new opencv-build version
  # - npm install ../opencv-build
  # - npm install
  # - cd test
  # - npm install
  # - npm run test-appveyor
